# Generated by Django 5.2.6 on 2025-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_service_categories',
            field=models.ManyToManyField(blank=True, help_text='Service categories that are free for this AMC user', related_name='amc_users_with_free_access', to='services.servicecategory'),
        ),
    ]
