# Generated by Django 5.2.6 on 2025-10-04 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(max_length=20)),
                ('service_address', models.TextField()),
                ('equipment_type', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('equipment_brand', models.CharField(blank=True, max_length=100)),
                ('equipment_model', models.CharField(blank=True, max_length=100)),
                ('problem_description', models.TextField()),
                ('work_performed', models.TextField()),
                ('date_of_service', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('total_time_taken', models.DurationField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Customer Approval'), ('APPROVED', 'Approved by Customer'), ('DECLINED', 'Declined by Customer')], default='PENDING', max_length=20)),
                ('customer_signature', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_job_sheets', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_sheet', to='services.servicerequest')),
            ],
            options={
                'verbose_name': 'Job Sheet',
                'verbose_name_plural': 'Job Sheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSheetMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateField()),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('job_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='services.jobsheet')),
            ],
            options={
                'verbose_name': 'Job Sheet Material',
                'verbose_name_plural': 'Job Sheet Materials',
                'ordering': ['date_used', 'id'],
            },
        ),
    ]
